# Generated by Django 2.1.3 on 2018-11-13 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('IdAlumno', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('apellidoPaternoAlumno', models.CharField(max_length=100)),
                ('apellidoMaternoAlumno', models.CharField(max_length=100)),
                ('nombreAlumno', models.CharField(max_length=100)),
                ('direccionAlumno', models.CharField(max_length=100)),
                ('telefonoAlumno', models.CharField(max_length=20)),
                ('emailAlumno', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perteneceAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servidorapi.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('IdClase', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Materia', models.CharField(max_length=100)),
                ('Horario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidoPaternoCoordinador', models.CharField(max_length=100)),
                ('apellidoMaternoCoordinador', models.CharField(max_length=100)),
                ('nombreCoordinador', models.CharField(max_length=100)),
                ('direccionCoordinador', models.CharField(max_length=100)),
                ('telefonoCoordinador', models.CharField(max_length=20)),
                ('email_Coordinador', models.CharField(max_length=50)),
                ('IdCoordinador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Coordinadores',
                'verbose_name': 'Coordinador',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidoPaternoDocente', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(max_length=100)),
                ('nombreDocente', models.CharField(max_length=100)),
                ('direccionDocente', models.CharField(max_length=100)),
                ('telefonoDocente', models.CharField(max_length=20)),
                ('emailDocente', models.CharField(max_length=50)),
                ('IdDocente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Docentes',
                'verbose_name': 'Docente',
            },
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('clave', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=100)),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servidorapi.Coordinador')),
            ],
        ),
        migrations.CreateModel(
            name='Parcial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.SmallIntegerField()),
                ('faltas', models.SmallIntegerField()),
                ('comentarios', models.CharField(max_length=100)),
                ('boletaPertenece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servidorapi.Boleta')),
            ],
        ),
        migrations.AddField(
            model_name='docente',
            name='escuelas',
            field=models.ManyToManyField(to='servidorapi.Escuela'),
        ),
        migrations.AddField(
            model_name='clase',
            name='docenteImpartiendo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servidorapi.Docente'),
        ),
        migrations.AddField(
            model_name='clase',
            name='escuelaImparte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servidorapi.Escuela'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='perteneceClase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servidorapi.Clase'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='clases',
            field=models.ManyToManyField(to='servidorapi.Clase'),
        ),
    ]
