# Generated by Django 2.1.3 on 2018-11-19 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servidorapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinador',
            name='IdCoordinador',
        ),
    ]
