# Generated by Django 2.1.3 on 2018-12-13 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servidorapi', '0003_coordinador_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='IdDocente',
        ),
        migrations.AddField(
            model_name='docente',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
